name: vil_editor
description: An IDE for ViL programming language.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  code_text_field: ^1.0.2
  flex_color_scheme: ^4.2.0
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_hooks: ^0.18.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  gap: ^2.0.0
  highlight: ^0.7.0
  hooks_riverpod: ^1.0.3
  intl: ^0.17.0
  supercharged: ^2.1.1
  vil:
    git:
      url: https://github.com/definev/vil.git
      path: vil

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/ttf/JetBrainsMono-Regular.ttf

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/ttf/JetBrainsMono-Regular.ttf
